--
-- Script was generated by Devart dbForge Studio for MySQL, Version 9.2.128.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12.04.2024 18:41:08
-- Server version: 8.0.30
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS `DB_platform_knock-knock`;

CREATE DATABASE `DB_platform_knock-knock`
CHARACTER SET utf8mb3
COLLATE utf8mb3_general_ci;

--
-- Set default database
--
USE `DB_platform_knock-knock`;

--
-- Create table `USER_LIST`
--
CREATE TABLE USER_LIST (
  ID int NOT NULL AUTO_INCREMENT,
  NUMBER char(11) NOT NULL,
  PASSWORD tinytext NOT NULL,
  ROLE char(10) NOT NULL DEFAULT 'USER',
  TYPE_OWNER char(15) NOT NULL,
  SURNAME char(30) NOT NULL,
  NAME char(30) NOT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 22,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `TOOLS`
--
CREATE TABLE TOOLS (
  T_NO int NOT NULL,
  DSEC char(40) NOT NULL,
  PRICE double(9, 2) NOT NULL,
  QTY double(9, 2) NOT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `ORDERS`
--
CREATE TABLE ORDERS (
  O_NO int NOT NULL,
  DATE date NOT NULL,
  C_NO int NOT NULL,
  T_NO int NOT NULL,
  QUANTITY double(9, 2) NOT NULL,
  AMOUNT double(9, 2) NOT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `CLIENTS`
--
CREATE TABLE CLIENTS (
  C_NO int NOT NULL,
  FIO char(40) NOT NULL,
  ADDR char(30) NOT NULL,
  CITY char(15) NOT NULL,
  PHONE char(11) NOT NULL,
  PRIMARY KEY (C_NO)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci,
ROW_FORMAT = DYNAMIC;

--
-- Create table `ADVERTISEMENT_LIST`
--
CREATE TABLE ADVERTISEMENT_LIST (
  id_advertisement int NOT NULL AUTO_INCREMENT,
  type_of_service tinytext NOT NULL,
  type_of_estate tinytext NOT NULL,
  owner_name tinytext NOT NULL,
  owner_tel tinytext NOT NULL,
  owner_type tinytext NOT NULL,
  name tinytext NOT NULL,
  address tinytext NOT NULL,
  price int NOT NULL,
  description text NOT NULL,
  rooms int NOT NULL,
  square int NOT NULL,
  image_name tinytext NOT NULL,
  PRIMARY KEY (id_advertisement)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci,
ROW_FORMAT = DYNAMIC;

-- 
-- Dumping data for table USER_LIST
--
INSERT INTO USER_LIST VALUES
(15, '89998887766', 'rrrrrrrr', '''USER''', 'Собственник', 'Алексеев', 'Иван'),
(19, 'root', 'pass', '''USER''', 'Собственник', 'Шушляков', 'Никита'),
(20, 'root', 'pass', '''USER''', 'Собственник', 'Федоров', 'Федор'),
(21, 'root', 'pass', '''USER''', 'Собственник', 'Васильев', 'Василий');

-- 
-- Dumping data for table TOOLS
--
-- Table `DB_platform_knock-knock`.TOOLS does not contain any data (it is empty)

-- 
-- Dumping data for table ORDERS
--
INSERT INTO ORDERS VALUES
(1, '2010-01-03', 1, 1, 1.00, 340.98);

-- 
-- Dumping data for table CLIENTS
--
INSERT INTO CLIENTS VALUES
(2, 'Петров', 'Мира 29', 'Екатеринбург', '-');

-- 
-- Dumping data for table ADVERTISEMENT_LIST
--
INSERT INTO ADVERTISEMENT_LIST VALUES
(1, 'commerceBuy', 'Офис', 'Никита', '89280140532', 'Риелтор', 'Офис 170кв.м.', 'Ставрополь, Кулакова 45.', 23000000, 'Продам офис', 1, 170, 'gajergjpwoje;ls;lgwe.jpg');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;